// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	model "the-drink-almanac-api/model"

	mock "github.com/stretchr/testify/mock"
)

// FavoriteStore is an autogenerated mock type for the FavoriteStore type
type FavoriteStore struct {
	mock.Mock
}

// CreateNewFavorite provides a mock function with given fields: favorite
func (_m *FavoriteStore) CreateNewFavorite(favorite model.Favorite) error {
	ret := _m.Called(favorite)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Favorite) error); ok {
		r0 = rf(favorite)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteFavorite provides a mock function with given fields: id
func (_m *FavoriteStore) DeleteFavorite(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields:
func (_m *FavoriteStore) FindAll() ([]model.Favorite, error) {
	ret := _m.Called()

	var r0 []model.Favorite
	if rf, ok := ret.Get(0).(func() []model.Favorite); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Favorite)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindFavoritesByUser provides a mock function with given fields: userId
func (_m *FavoriteStore) FindFavoritesByUser(userId string) ([]model.Favorite, error) {
	ret := _m.Called(userId)

	var r0 []model.Favorite
	if rf, ok := ret.Get(0).(func(string) []model.Favorite); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Favorite)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewFavoriteStore interface {
	mock.TestingT
	Cleanup(func())
}

// NewFavoriteStore creates a new instance of FavoriteStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFavoriteStore(t mockConstructorTestingTNewFavoriteStore) *FavoriteStore {
	mock := &FavoriteStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
