FROM golang:1.18.1

RUN export GOPATH="$HOME/go"
RUN PATH="$GOPATH/bin:$PATH"

WORKDIR /the-drink-almanac-api

RUN go install gotest.tools/gotestsum@latest

COPY go.mod go.sum ./

RUN go mod download

COPY . ./

ENTRYPOINT [ "gotestsum", "--format", "testname" ]